CREATE TABLE "tb_studio_settings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"studio_name" text DEFAULT 'JM Fitness Studio' NOT NULL,
	"email" text DEFAULT 'contato@jmfitness.com' NOT NULL,
	"phone" text DEFAULT '(21) 98099-5749' NOT NULL,
	"address" text DEFAULT 'Rua das Flores, 123' NOT NULL,
	"city" text DEFAULT 'Rio de Janeiro' NOT NULL,
	"state" text DEFAULT 'RJ' NOT NULL,
	"zip_code" text DEFAULT '20000-000' NOT NULL,
	"monday_open" text DEFAULT '06:00' NOT NULL,
	"monday_close" text DEFAULT '22:00' NOT NULL,
	"tuesday_open" text DEFAULT '06:00' NOT NULL,
	"tuesday_close" text DEFAULT '22:00' NOT NULL,
	"wednesday_open" text DEFAULT '06:00' NOT NULL,
	"wednesday_close" text DEFAULT '22:00' NOT NULL,
	"thursday_open" text DEFAULT '06:00' NOT NULL,
	"thursday_close" text DEFAULT '22:00' NOT NULL,
	"friday_open" text DEFAULT '06:00' NOT NULL,
	"friday_close" text DEFAULT '22:00' NOT NULL,
	"saturday_open" text,
	"saturday_close" text,
	"sunday_open" text,
	"sunday_close" text,
	"monthly_fee_default" integer DEFAULT 15000 NOT NULL,
	"registration_fee" integer DEFAULT 5000 NOT NULL,
	"personal_training_hourly_rate" integer DEFAULT 10000 NOT NULL,
	"payment_due_date_default" integer DEFAULT 10 NOT NULL,
	"grace_period_days" integer DEFAULT 5 NOT NULL,
	"max_check_ins_per_day" integer DEFAULT 2 NOT NULL,
	"allow_weekend_check_in" boolean DEFAULT false NOT NULL,
	"terms_and_conditions" text,
	"privacy_policy" text,
	"cancellation_policy" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
